### ISSUE TITLE
Not and Issue, but Feature Request

### ISSUE THREAD

**Issue by Ticskter** [benbenlaw/skyopolis-5#10]
in other mod packs there is a feature/mod that would allow you to craft the pebbles into a 2x2 crafting grid just by pressing "K". this could be a great feature/mod implementation since most of the resources at the beginning of the mod pack come from blank pebbles and blank dusts. it would make the opening stages of Skyopolis 5 a little more fluid and a little faster i believe.

**Comment by benbenlaw** [comment]
im not sure what mod its from if its from botania then it wont be added

**Comment by Ticskter** [comment]
i don't know why i didn't just research this myself before posting but the mod is called Crafting Tweaks. i just removed it from another mod pack that is 1.18 and placed it in and its working as intended. there is a small key conflict for quark block rotation, which i just unbind anyway.
