### ISSUE TITLE
Crush before minecraft can start

### ISSUE THREAD

**Issue by Diegio** [benbenlaw/skyopolis-5#12]
When i try to play at the modpack it don't run and 
it refers to the minecraft launcher telling me there is a problem with the java runtime environment, what can I do?

**Comment by benbenlaw** [comment]
is there a crash report?

**Comment by Diegio** [comment]
![Immagine 2022-06-27 133947](https://user-images.githubusercontent.com/108274333/175933119-9c9901e2-4f8b-4feb-8993-3124208cb4ec.jpg)

**Comment by Diegio** [comment]
Sorry it's in italian

**Comment by benbenlaw** [comment]
there should be a crash report in the install location for the mod pack as well

**Comment by Diegio** [comment]
Sorry now i have to go to lunch, when i finished i send you the crah report

**Comment by Diegio** [comment]
Sorry but what can i do for that?

**Comment by Rodderik** [comment]
I'm got the same issue on a fresh install of CurseForge. Vanilla starts fine. The log doesn't reveal much.
[latest.log](https://github.com/benbenlaw/skyopolis-5/files/9021250/latest.log)

I did download JAVA from the link in the server pack and add the suggested JAVA arguments. One of those seems to fix the launching issue.

**Comment by Vikbor5342** [comment]
This issue seems to be caused by the java version developed by microsoft that curseforge use.
To fix this please install java 17 from [Oracle](https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe) https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe
