### ISSUE TITLE
Quark Blossom Trees in Bonsai Pots

### ISSUE THREAD

**Issue by 2xTialos** [benbenlaw/skyopolis-5#16]
Quark Blossom Trees have a Unique log, the Blossom, however, in this pack, using a Bonsai Pot grows them with Oak. This is a MASSIVE error, as these trees are incredibly large, and this makes the only way to get this log through growing the tree itself

**Comment by moody69420** [comment]
i would suggest checking tickets before making a duplicate ticket next time
