### ISSUE TITLE
Early Progression simplification

### ISSUE THREAD

**Issue by 2xTialos** [benbenlaw/skyopolis-5#17]
Lava, at least early game, is INCREADIBLY hard to reasonably acquire, due to it ONLY being available from one resource, which is either INCREDIBLY hard to find in that dimension[because holy hell that dimension sucks to explore], or get lucky with nugget conversion. A suggestion I have would be to make it so Rotspawn of any type can spawn in the overworld ONLY on Underdark materials, making the only other source of Utherium at least somewhat viable to be in control of.

**Comment by moody69420** [comment]
u should be glad it makes more lava then it did before. also mining the ore isnt that bad, if u cant find it ur probably not looking in the right biome

**Comment by 2xTialos** [comment]
considering you can't check where it spawns or anything about it, it's rather hard to locate

**Comment by moody69420** [comment]
Or like I did u could have asked in the undergarden discord since they reworked ore spawns for 1.18 they would have told u that ore is biome based and vanilla ore is in the ceiling after that I found loads

**Comment by benbenlaw** [comment]
try the latest update theres a bunch of changes
