### ISSUE TITLE
Recipe for Red Mushroom borked

### ISSUE THREAD

**Issue by SudzBud** [benbenlaw/skyopolis-5#18]
Looks like since brown mushroom is on the 'any-undergarden. mushroom' + seeds recipe = brown muchroom, I cannot craft the red mushroom.

**Comment by Pinguin34** [comment]
You can change the recipe in a crafting table with the double circle arrow

**Comment by SudzBud** [comment]
ah, was using tinkers craft table and that isn't an option. thanks for the
work-around without cheating one in
