### ISSUE TITLE
Quest Issues

### ISSUE THREAD

**Issue by IHvABadUsername** [benbenlaw/skyopolis-5#21]
I completed all the tasks up to the "Undergarden Enriching Water" but the quest is still greyed out. Please Hel
![Screen Shot 2022-07-08 at 3 49 27 PM](https://user-images.githubusercontent.com/45613482/178079453-1799d11c-ed91-4a26-8a50-ce5cbe910490.png)
p

**Comment by moody69420** [comment]
you need to finish the quest before it unlocks then next ones

**Comment by IHvABadUsername** [comment]
as you can see they are all green. I finished all the quests until this one. Do you know which one I may be missing?

**Comment by cslewislives** [comment]
The main Undergarden Catalyst Quest is available. You have to finish the center quest before you can open the next ones

**Comment by IHvABadUsername** [comment]
i have the item but the center quest is greyed out which in turn does not let me submit the item

**Comment by moody69420** [comment]
iirc its a checkmark quest

**Comment by cslewislives** [comment]
From that picture the Catalyst Quest is a lighter grey than the others, meaning it's available to submit. Can you show what it looks like when you click on it?

**Comment by IHvABadUsername** [comment]
had to relaunch and it fixed itself...

**Comment by IHvABadUsername** [comment]
Thank you all
