### ISSUE TITLE
Lag with Refined Storage Exporters

### ISSUE THREAD

**Issue by RudiHansen** [benbenlaw/skyopolis-5#26]
I swithed my Simple Storage system out with Refined Storage, and now my game lags quite a bit.
When I open the Crafting Grid or any Chests there is a 2-3 second delay.

I do have quite a few items stored in Drawers, and 6 almost full Diamond chests, but I did not have any problems before i changed to Refined Storage.

The problem seems to be related to 2 Exporters with one stack upgrade each, I have that export Cobblestone into 2 Quantum Compressors, when I turn them off the lag disappeares.

But should they not be able to handle exporting items like that?

**Comment by Gurkysword12** [comment]
Cant do anything about that. I have updated the mod that may fix it. If it doesn't report it to their Github
