### ISSUE TITLE
impossible de join mon monde

### ISSUE THREAD

**Issue by xbeerkill3rxx** [benbenlaw/skyopolis-5#27]
bonjours,

quand j'essaye d'aller en solo ou meme sur serveur mon jeux reste bloquer sur join the game, on est plusieures de mes amies a avoir se soucis est'ce que c'est un soucis du pack?

**Comment by Gulingo** [comment]
I'm having the same issue as you, let me know if you find a solution. :D

**Comment by moody69420** [comment]
if ur using curseforge the java 17 they use wont work for skyopolis 5

**Comment by TorreyF** [comment]
same issue and I tried a fresh install, still happens

**Comment by Flexo013** [comment]
Same here. Both with existing servers and creating a new single player world. Version is 5.3.0.

**Comment by benbenlaw** [comment]
update to modpack on the way

**Comment by Flexo013** [comment]
Issue can be closed as it is fixed by the 3.1 update.
