### ISSUE TITLE
guide book not working

### ISSUE THREAD

**Issue by golden3333** [benbenlaw/skyopolis-5#28]
the guide book isn't working

**Comment by VladStanimir** [comment]
I am also affected by this and have found a workaround.

The 3.1 version of the  pack is missing the patchouli_books content from the overrides folder however the 3.0 version does not.

You can download the 3.0 version form  https://www.curseforge.com/minecraft/modpacks/skyopolis-5/files/3898676 and copy the contents of the  patchouli_books sub folder from overrides to your instances patchouli_books sub folder, then start up the instance.

After you start the world run the command /give @p patchouli:guide_book{"patchouli:book":"patchouli:skyopolis"} if you lost your book or the guide book is brown and not cyan

**Comment by Gurkysword12** [comment]
Fixed in dev
