### ISSUE TITLE
Not generating other islands

### ISSUE THREAD

**Issue by francybo** [benbenlaw/skyopolis-5#30]
Hi, my skyopolis 5 pack in not generating Islands around my principal one... I tried to delete and download again the pack, but nothing... (Generate structures is on)

**Comment by kalutro** [comment]
I am having this same issue. I recently starting this pack again and noticed the small islands in the overworld were missing, but thought it was a design change. I am currently in the nether and have been searching forever for the ore islands mentioned in the quests. After about an hour I finally checked a video and have realized they do not exist in my world. I get slime islands, bastions and fortresses. This makes the pack unable to be completed as I have no access to cobalt. I am on version 4.1.

**Comment by Novtalath** [comment]
As I said on Discord - until one of the maintainers will release the pack version, that works - you need to download the older version of the SkyblockBuilder mod (SkyblockBuilder-1.18.2-3.3.18) and replace it in your pack. That will fix the issue temporarily.
