### ISSUE TITLE
Space Portal Frame no longer exists

### ISSUE THREAD

**Issue by JustinBerger** [benbenlaw/skyopolis-5#32]

**Comment by Wibbbs** [comment]
I have run into this issue. I was able to use the teleporter to get deep space but is there anyway to mare the invalid quests as complete?

![IMG_6536](https://github.com/benbenlaw/skyopolis-5/assets/24574428/79dfa5be-daa2-4a5f-aea1-f74e4c74bb2d)

**Comment by Wibbbs** [comment]
nevermind I found the below.

https://faq.ftb.world/books/ftb-quests-112/page/how-to-use---for-modpack-creators

*To become an editor, type /ftbquests editing_mode command (You don't have to have cheats enabled in singleplayer worlds for this command to work). New buttons will show up in the Quest GUI.*


You need to go in Edit mode and then right click the quest and there should be Complete option, then exit Edit mode to continue playing...
