### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by benbenlaw** [benbenlaw/skyopolis-5#6]
![image](https://user-images.githubusercontent.com/42780877/171821568-67f8e722-ac1e-4b07-b7ca-37c1ab746770.png)
dont click this makes cras
[crash-2022-06-03_09.42.37-client.txt](https://github.com/benbenlaw/skyopolis-5/files/8831048/crash-2022-06-03_09.42.37-client.txt)
h

**Comment by Gurkysword12** [comment]
Seems to be flywheel related

**Comment by Gurkysword12** [comment]
seems to not happen anymore
